service: linka
runtime: python39

handlers:
  # Assets hashados de Vite (cache largo)
  - url: /assets
    static_dir: dist/assets
    http_headers:
      Cache-Control: "public, max-age=31536000, immutable"

  # Otros archivos estáticos comunes (js, css, imágenes, fuentes, mapas, etc.)
  - url: /(.*\.(js|css|png|jpg|jpeg|gif|svg|ico|txt|json|webp|woff2?|mp4|webm|map))
    static_files: dist/\1
    upload: dist/(.*\.(js|css|png|jpg|jpeg|gif|svg|ico|txt|json|webp|woff2?|mp4|webm|map))
    http_headers:
      Cache-Control: "public, max-age=31536000, immutable"

  # Fallback SPA: cualquier otra ruta -> index.html
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    http_headers:
      Cache-Control: "no-store"
